spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/messanger
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
