version: "1.0"
services:
  app:
    image: 'messenger:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/messenger
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - "8888:8080"

  postgres:
    image: "postgres:13.1-alpine"
    environment:
      POSTGRES_DB: "messenger"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5440:5432"