create table messages
(
    id      int8 generated by default as identity,
    message varchar(255),
    user_id varchar(255),
    primary key (id)
);
create table users
(
    username varchar(255) not null,
    password varchar(255),
    primary key (username)
);
alter table if exists messages
    add constraint FKpsmh6clh3csorw43eaodlqvkn foreign key (user_id) references users (username);

insert into users
values ('Петр', 'root'),
       ('Наташа', 'admin')